# @package taint 
# This is the yaml file for panda 
# So, all config necessary to run panda taint analysis
source_string: "git clone -b spitfire_0 https://github.com/panda-re/panda.git"
panda_container: panda
qcow: "http://panda-re.mit.edu/qcows/linux/ubuntu/1804/x86_64/bionic-server-cloudimg-amd64.qcow2"
max_label_set_size: 16
max_label_set_compute_distance: 16
max_pcs_for_an_fbs: 16
max_fbs_for_a_pc: 16
input_file: "/default/seeds/slashdot.xml" #"/seed-corpus/not_kitty.tiff"
args: "file" #"-c jpeg file out.jpeg"
plog_filename: "taint.plog" 
