# @package manager 
name: aflfast 
max_pods: 10 
cron_sched: "*/1 * * * *"
schedule: "EXPLORE"
MAP_SIZE: 65536
HAVOC_CYCLES_INIT: 1024
HAVOC_CYCLES: 256
POWER_BETA: 1
HAVOC_MAX_MULT: 16
SKIP_TO_NEW_PROB: 99
SKIP_NFAV_OLD_PROB: 95
SKIP_NFAV_NEW_PROB: 75


